module.exports = Object.freeze({
  MAIN: [
    '@react-navigation/native',
    '@react-navigation/stack',
    '@react-navigation/drawer',
    'react-native-reanimated',
    'react-native-gesture-handler',
    'react-native-screens',
    'react-native-safe-area-context',
    'react-native-safe-area-view',
    'react-native-paper',
    '@react-native-community/masked-view',
    '@react-native-community/async-storage',
    '@react-native-community/datetimepicker',
    'react-native-vector-icons',
    'react-native-loading-spinner-overlay',
    'react-native-image-picker',
    'lodash',
    'yup',
    'axios',
    'formik',
    'moment',
    'react-native-keyboard-aware-scroll-view',
    '@codepso/rn-helper',
  ],
  REDUX: [
    'redux',
    'react-redux',
    'redux-persist',
  ],
  LANG: [
    'i18n-js',
    'react-native-localize',
  ]
});
